import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Butic64</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>Butic64 СI/CD добавлен. Тест 5</h1>
    </>
  );
}
