import Head from 'next/head';
import Image from 'next/image';
import logo from '@/public/assets/icons/logo.svg';
export default function Home() {
  return (
    <>
      <Head>
        <title>Butic64</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Image className="logo" src={logo} alt="Picture of the author"></Image>
    </>
  );
}
