name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install
          npm install next-transpile-modules

      - name: Build Application
        run: |
          npm run build

      - name: Debug Private Key
        run: echo "$SSH_PRIVATE_KEY"

      - name: Set up SSH
        run: |
          mkdir -p $HOME/.ssh
          echo "" > $HOME/.ssh/known_hosts
          ssh-keyscan -H 212.233.77.110 >> $HOME/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/private_key.pem
          chmod 600 $HOME/.ssh/private_key.pem

      - name: Deploy to Remote Server
        run: |
          ssh -i $HOME/.ssh/private_key.pem ubuntu@212.233.77.110 "cd /var/www/nextjs/butic64 && git pull origin main && npm install && pm2 restart nextjs"
